<?php defined('_JEXEC') or die;
use Joomla\CMS\MVC\Model\BaseDatabaseModel;

class Railway2ModelCocons extends BaseDatabaseModel {
	public $thread;

	public static function getInstance($type, $prefix = '', $config = array())
	{
		return parent::getInstance($type, $prefix, $config); // TODO: Change the autogenerated stub
	}

	public function checkCocon($uid1, $uid2)
    {
        $thread1 = explode('_', $uid1);
        $thread2 = explode('_', $uid2);
        return ($thread1[0] == $thread2[0] && $thread1[2] == $thread2[2]) ? true : false;
    }

	public function getCocons()
    {
        $db =& $this->getDbo();
        $query = $db->getQuery(true);
        $query
            ->select('*')
            ->from($db->quoteName('#__rw2_cocons'));
        return $db->setQuery($query)->loadObjectList();
    }

	public function setCocon()
    {
        $this->thread = JFactory::getApplication()->input->getString('thread', false);
        if (!$this->thread || !$this->checkAccess()) return json_encode(array('code'=>'-1','message'=>'Not avalible, thread'.$this->thread));
        $db =& $this->getDbo();
        $query = $db->getQuery(true);
        $query
            ->insert($db->quoteName("#__rw2_cocons"))
            ->columns($db->quoteName(array('dat', 'thread')))
            ->values("CURRENT_DATE(), ".$db->quote($this->thread));
        try {
            $result = $db->setQuery($query)->execute();
        }
        catch (Exception $e)
        {
            $arr['code'] = (string) $e->getCode();
            $arr['message'] = $e->getMessage();
        }
        return (!$result) ? json_encode($arr) : json_encode(array('code'=>'200','message'=>'Запомнено'));
    }

	public function delCocon()
    {
        $this->thread = JFactory::getApplication()->input->getString('thread', false);
        if (!$this->thread || !$this->checkAccess()) return json_encode(array('code'=>'-1','message'=>'Not avalible, thread'.$this->thread));
        $db =& $this->getDbo();
        $query = $db->getQuery(true);
        $query
            ->delete($db->quoteName("#__rw2_cocons"))
            ->where($db->quoteName('thread')." LIKE ".$db->quote($this->thread));
        try {
            $result = $db->setQuery($query)->execute();
        }
        catch (Exception $e)
        {
            $arr['code'] = (string) $e->getCode();
            $arr['message'] = $e->getMessage();
        }
        return (!$result) ? json_encode($arr) : json_encode(array('code'=>'200','message'=>'Запомнено'));
    }

    /* Проверка прав */
    private function checkAccess()
    {
        return JFactory::getUser()->authorise('core.add', 'com_railway2');
    }
}