<?php
defined('_JEXEC') or die;

class Railway2ModelDirections extends JModelLegacy {
    public static function getInstance($type, $prefix = '', $config = array())
    {
        return parent::getInstance($type, $prefix, $config); // TODO: Change the autogenerated stub
    }

    public function getDirections()
    {
        $db = JFactory::getDbo();
        $query = $db->getQuery(true);
        $query
            ->select('*')
            ->from('#__rw2_directions_list')
            ->where("`telegram` = '1'")
            ->order('title');
        $db->setQuery($query);
        return $db->loadAssocList();
    }
}