<?php
defined('_JEXEC') or die;
use Joomla\CMS\MVC\Model\BaseDatabaseModel;

class Railway2ModelMobile extends BaseDatabaseModel {
    public static function getInstance($type='Mobile', $prefix = 'Railway2Model', $config = array())
    {
        return parent::getInstance($type, $prefix, $config); // TODO: Change the autogenerated stub
    }

    public function getMobile()
    {
        $db =& $this->getDBO();
        $query = $db->getQuery(true);
        $query
            ->select('*')
            ->from($db->quoteName("#__rw2_mobile"));
        $result = $db->setQuery($query)->loadAssocList();
        return array("Station" => $result);
    }

    /* Инфа о кассах */
    public function getDescTime()
    {
        $id = JFactory::getApplication()->input->getInt('id', 0);
        if ($id == 0) return false;
        $db = JFactory::getDbo();
        $query = $db->getQuery(true);
        $query
            ->select('`t`.*, `u`.`name` as `user`, `v`.`variant`')
            ->from('#__rw2_station_tickets as `t`')
            ->where("`stationID` = {$id}")
            ->leftJoin('#__rw2_turnstile_variants as `v` ON `v`.`id` = `t`.`turnstiles`')
            ->leftJoin('#__users as `u` ON `u`.`id` = `t`.`thanks`');
        $db->setQuery($query);
        $result = $db->loadObjectList();
        if (count($result) < 1) return false;
        $ret = array();
        foreach ($result as $item) {
            $ret[] = self::normalTime($item->time_1, $item->time_2, $item->turnstiles, $item->tpd).' ('.JText::_('COM_RAILWAY2_TIMEMASK_'.$item->timemask.'_SHORT').')';
        }
        return array("desc" => implode(', ', $ret));
    }
    static function normalTime($t1, $t2, $turn, $tpd)
    {
        $result = date("H.i", strtotime(date("Y-m-d ".$t1))).' - '.date("H.i", strtotime(date("Y-m-d ".$t2)));
        if (($t1 == '00:00:00' && $t2 == '23:59:59') || ($t1 == null && $t2 == null && $turn != null)) $result = JText::_('COM_RAILWAY2_DESC_EVERYTIME');
        if ($t1 == null && $t2 == null && $turn == null && $tpd == '0') $result = JText::_('COM_RAILWAY2_SCHEME_DESC_NO_DESC');
        if ($tpd != '0') $result = JText::_('COM_RAILWAY2_SCHEME_DESC_TPD_DESC');
        return $result;
    }
}