<?php defined('_JEXEC') or die;
require_once JPATH_BASE.'/components/com_railway2/helpers/online.php';

class Railway2ModelSync extends JModelLegacy {
	public $archive;

	public static function getInstance($type, $prefix = '', $config = array())
	{
		return parent::getInstance($type, $prefix, $config); // TODO: Change the autogenerated stub
	}


	public function sync()
	{
		$this->archive = JFactory::getApplication()->input->getBool('archive', false);

		$result = $this->syncRailway();

		return $result;
	}

	/* Синхронизация железки */
	private function syncRailway()
	{
		jimport('phpQuery-onefile');

		$dir = Railway2HelperOnline::getDirection();
		$controlPoint = Railway2HelperOnline::getControlPoint($dir);
		$url = Railway2HelperOnline::getURL($controlPoint->express);

		$result['dir'] = $dir;
		$result['date'] = Railway2HelperCodes::getCurrentDate('Y-m-d');
		$result['controlID'] = $controlPoint->stationID;
		$result['controlExpress'] = $controlPoint->express;
		$result['URL'] = $url;

		$d = phpQuery::newDocumentHtml(file_get_contents($url));

		$tmp = new phpQueryObject($d->find('div.trlist__cell-pointdata__tr-num'));
		$time_type = 1; //1 - Время прибытия, 2 - время отправления
		$res = array();
		foreach ($d->find("tr[id^='tr'] > td") as $fnd) {
			$tmp = trim(pq($fnd)->text());
			if (preg_match('/\d{4}$/', $tmp) == 1) {
				$res[$tmp] = array();
				$num = $tmp;
				$res[$num]['express'] = $controlPoint->express; //Экспресс-3 код станции
			}
			if (preg_match('/\d{2}:\d{2}$/', $tmp) == 1 && $time_type == 1) {
				if (empty($res[$num]['arr'])) $res[$num]['arr'] = $tmp; //Время прибытия
				$time_type = 2;
			}
			if (preg_match('/\d{2}:\d{2}$/', $tmp) == 1 && $time_type == 2) {
				$res[$num]['dep'] = $tmp; //Время отправления
				$time_type = 1;
			}
			if (preg_match('/ - /', $tmp) == 1) {
				$res[$num]['route'] = $tmp; //Маршрут собаки
			}
			if (preg_match('/Поезд/', $tmp) == 1) {
				$status = str_ireplace(array('по графику', 'с опозданием'), array(' по графику', ' с опозданием'), $tmp);
				if (preg_match_all('/Поезд отправился со ст. ([\W\w]{2,}) с опозданием на (\d+)([\W\w]{2,})/', $status, $f, PREG_PATTERN_ORDER) == 1 || preg_match_all('/Поезд прибыл на ст. ([\W\w]{2,}) с опозданием на (\d+)([\W\w]{2,})/', $status, $f, PREG_PATTERN_ORDER) == 1) {
					$res[$num]['status'] = $f[2][0]; //Задержка
					$res[$num]['station'] = Railway2HelperOnline::validStationName($f[1][0]); //Название станции, которую проследовал или на которую прибыл поезд
				}
				if (preg_match_all('/Поезд отправился со ст. ([\W\w]{2,}) по графику/', $status, $f, PREG_PATTERN_ORDER) == 1 || preg_match_all('/Поезд прибыл на ст. ([\W\w]{2,}) по графику/', $status, $f, PREG_PATTERN_ORDER) == 1) {
					$res[$num]['status'] = 0;
					$res[$num]['station'] = Railway2HelperOnline::validStationName($f[1][0]); //Название станции, которую проследовал или на которую прибыл поезд
				}
				$num = '';
			}
			if (preg_match('/нет/', $tmp) == 1) {
				unset($res[$num]);
				$num = '';
			}
		}

		$result['res'] = $res;
		if (!empty($res)) $this->exportToBaseRW($dir, $res);

		return (!empty($res)) ? $result : JText::_('COM_RAILWAY2_MGT_STAT_ERROR_EMPTY');
	}

	private function exportToBaseRW($dir, $data)
	{
		$db = JFactory::getDbo();
		$query = 'INSERT INTO `#__rw2_online` (`dat`, `directionID`, `num`, `station`, `latence`) VALUES ';
		$values = array();
		foreach ($data as $num => $item) {
			$station = $item['station'];
			$latence = $item['status'];
			$values[] = "(CURRENT_DATE(), '{$dir}', '{$num}', '{$station}', '{$latence}')";
		}
		$query .= implode(',', $values);
		$query .= " ON DUPLICATE KEY UPDATE `station`=VALUES(`station`), `latence`=VALUES(`latence`), `stamp` = CURRENT_TIMESTAMP()";

		$db->setQuery($query);
		$db->query();
		return true;
	}
}